# -*- coding: utf-8 -*-
"""Generate assets/css/zt-icons.css (mask-image icon font used by the Elementor
icon picker and by <i class="zti zti-NAME"> markup) from assets/icons/sprite.svg."""
import os
import re
import urllib.parse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPRITE = os.path.join(ROOT, 'ziteh-core', 'assets', 'icons', 'sprite.svg')
OUT = os.path.join(ROOT, 'ziteh-core', 'assets', 'css', 'zt-icons.css')

s = open(SPRITE, encoding='utf-8').read()
rules = ['/*! Ziteh icons (generated by tools/build_icons.py) */',
         '.zti{display:inline-block;width:1em;height:1em;vertical-align:-.125em;background-color:currentColor;'
         '-webkit-mask:var(--zti) center/contain no-repeat;mask:var(--zti) center/contain no-repeat;font-style:normal}']
for m in re.finditer(r'<symbol([^>]*)>(.*?)</symbol>', s, flags=re.S):
    attrs, inner = m.group(1), m.group(2)
    name = re.search(r'id="i-([\w-]+)"', attrs).group(1)
    attrs = re.sub(r'\s*id="[^"]*"', '', attrs).replace('currentColor', '#000')
    inner = inner.replace('currentColor', '#000')
    svg = '<svg xmlns="http://www.w3.org/2000/svg"%s>%s</svg>' % (attrs, inner)
    uri = 'data:image/svg+xml,' + urllib.parse.quote(svg, safe=' =:/"-.,')
    rules.append('.zti-%s{--zti:url("%s")}' % (name, uri.replace('"', "'")))
open(OUT, 'w', encoding='utf-8').write('\n'.join(rules) + '\n')
print('icons:', len(rules) - 2)
